/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.setSize(200, 250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuPopup = new javax.swing.JPopupMenu();
        mnuBackGround = new javax.swing.JMenu();
        mnuRed = new javax.swing.JMenuItem();
        mnuBlue = new javax.swing.JMenuItem();
        mnuForeground = new javax.swing.JMenu();
        mnuYellow = new javax.swing.JMenuItem();
        mnuPink = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuOpen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuClose = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuQuit = new javax.swing.JMenuItem();
        mnuCustom = new javax.swing.JMenu();
        mnuCustom1 = new javax.swing.JCheckBoxMenuItem();
        menuCustom2 = new javax.swing.JMenu();
        mnuCustom21 = new javax.swing.JRadioButtonMenuItem();
        mnuCustom22 = new javax.swing.JRadioButtonMenuItem();

        mnuBackGround.setText("Background");
        mnuBackGround.setComponentPopupMenu(mnuPopup);

        mnuRed.setBackground(new java.awt.Color(255, 0, 0));
        mnuRed.setText("Red");
        mnuRed.setOpaque(true);
        mnuRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRedActionPerformed(evt);
            }
        });
        mnuBackGround.add(mnuRed);

        mnuBlue.setBackground(new java.awt.Color(0, 0, 204));
        mnuBlue.setText("Blue");
        mnuBlue.setBorderPainted(true);
        mnuBlue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnuBlue.setOpaque(true);
        mnuBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBlueActionPerformed(evt);
            }
        });
        mnuBackGround.add(mnuBlue);

        mnuPopup.add(mnuBackGround);

        mnuForeground.setText("Foreground");
        mnuForeground.setComponentPopupMenu(mnuPopup);

        mnuYellow.setBackground(new java.awt.Color(255, 255, 51));
        mnuYellow.setText("Yellow");
        mnuYellow.setOpaque(true);
        mnuYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuYellowActionPerformed(evt);
            }
        });
        mnuForeground.add(mnuYellow);

        mnuPink.setBackground(new java.awt.Color(255, 153, 153));
        mnuPink.setText("Pink");
        mnuPink.setOpaque(true);
        mnuPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPinkActionPerformed(evt);
            }
        });
        mnuForeground.add(mnuPink);

        mnuPopup.add(mnuForeground);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setColumns(20);
        txt1.setRows(5);
        txt1.setComponentPopupMenu(mnuPopup);
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txt1);

        mnuFile.setText("File");

        mnuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        mnuOpen.setText("Open");
        mnuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mnuOpen);
        mnuFile.add(jSeparator1);

        mnuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuClose.setText("Close");
        mnuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCloseActionPerformed(evt);
            }
        });
        mnuFile.add(mnuClose);
        mnuFile.add(jSeparator2);

        mnuQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        mnuQuit.setText("Quit");
        mnuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuQuit);

        jMenuBar1.add(mnuFile);

        mnuCustom.setText("Custom");

        mnuCustom1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        mnuCustom1.setSelected(true);
        mnuCustom1.setText("Custom1");
        mnuCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustom1ActionPerformed(evt);
            }
        });
        mnuCustom.add(mnuCustom1);

        menuCustom2.setText("Custom2");

        mnuCustom21.setSelected(true);
        mnuCustom21.setText("Custome21");
        mnuCustom21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustom21ActionPerformed(evt);
            }
        });
        menuCustom2.add(mnuCustom21);

        mnuCustom22.setSelected(true);
        mnuCustom22.setText("Customer22");
        mnuCustom22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustom22ActionPerformed(evt);
            }
        });
        menuCustom2.add(mnuCustom22);

        mnuCustom.add(menuCustom2);

        jMenuBar1.add(mnuCustom);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenActionPerformed
       JOptionPane.showMessageDialog(this, "Menu Open is clicked.");
    }//GEN-LAST:event_mnuOpenActionPerformed

    private void mnuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCloseActionPerformed
        JOptionPane.showMessageDialog(this, "Menu Clode 1 is clicked.");
    }//GEN-LAST:event_mnuCloseActionPerformed

    private void mnuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuQuitActionPerformed

    private void mnuCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustom1ActionPerformed
        if (this.mnuCustom1.isSelected()) {
            JOptionPane.showMessageDialog(this, "Menu Custome1 is selected.");
        }else{
            JOptionPane.showMessageDialog(this, "Menu Custome1 is de-selected.");
        }
    }//GEN-LAST:event_mnuCustom1ActionPerformed

    private void mnuCustom21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustom21ActionPerformed
        if (this.mnuCustom21.isSelected()) {
            JOptionPane.showMessageDialog(this, "Menu Custome21 is selected.");
        }else{
            JOptionPane.showMessageDialog(this, "Menu Custome22 is de-selected.");
        }
    }//GEN-LAST:event_mnuCustom21ActionPerformed

    private void mnuCustom22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustom22ActionPerformed
        if (this.mnuCustom22.isSelected()) {
            JOptionPane.showMessageDialog(this, "Menu Custome22 is selected.");
        }else{
            JOptionPane.showMessageDialog(this, "Menu Custome22 is de-selected.");
        }
    }//GEN-LAST:event_mnuCustom22ActionPerformed

    private void mnuRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRedActionPerformed
        this.txt1.setBackground(mnuRed.getBackground());
    }//GEN-LAST:event_mnuRedActionPerformed

    private void mnuBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBlueActionPerformed
        this.txt1.setBackground(mnuBlue.getBackground());
    }//GEN-LAST:event_mnuBlueActionPerformed

    private void mnuYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuYellowActionPerformed
        this.txt1.setBackground(mnuYellow.getBackground());
    }//GEN-LAST:event_mnuYellowActionPerformed

    private void mnuPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPinkActionPerformed
        this.txt1.setBackground(mnuPink.getBackground());
    }//GEN-LAST:event_mnuPinkActionPerformed

    private void txt1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseReleased
        if (evt.isPopupTrigger()) {
            this.mnuPopup.show(this.txt1, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_txt1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuCustom2;
    private javax.swing.JMenu mnuBackGround;
    private javax.swing.JMenuItem mnuBlue;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JMenu mnuCustom;
    private javax.swing.JCheckBoxMenuItem mnuCustom1;
    private javax.swing.JRadioButtonMenuItem mnuCustom21;
    private javax.swing.JRadioButtonMenuItem mnuCustom22;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuForeground;
    private javax.swing.JMenuItem mnuOpen;
    private javax.swing.JMenuItem mnuPink;
    private javax.swing.JPopupMenu mnuPopup;
    private javax.swing.JMenuItem mnuQuit;
    private javax.swing.JMenuItem mnuRed;
    private javax.swing.JMenuItem mnuYellow;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables
}
