package Internationalization;

import java.text.MessageFormat;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

public class CompoundMessageDemo extends javax.swing.JFrame {

    String base = "Internationalization/message";
    ResourceBundle resource;
    
    public CompoundMessageDemo() {
        initComponents();
//        this.setSize(300, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbLocale = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compound Message");
        setBackground(new java.awt.Color(51, 204, 255));

        cbLocale.setBackground(new java.awt.Color(255, 255, 0));
        cbLocale.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        cbLocale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "US", "VietNam", "Germany" }));
        cbLocale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(cbLocale, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(cbLocale, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLocaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocaleActionPerformed
        Locale curLocale = null;
        int index = cbLocale.getSelectedIndex();
        if (index == 1) curLocale = new Locale("en", "US");
        if (index == 2) curLocale = new Locale("vi", "VN");
        if (index == 3) curLocale = new Locale("de", "DE");
        resource = ResourceBundle.getBundle(base, curLocale);
        //Setup message array of arguaments
        Object[] messageArguments = {
            resource.getString("planet"),
            new Integer(7),
            new Date()
        };
        //create formatter
        MessageFormat formatter = new MessageFormat("");
        formatter.setLocale(curLocale);
        //Format the Message Using the Pattern and the Arguements
        formatter.applyPattern(resource.getString("template"));
        String output = formatter.format(messageArguments);
        //output message
        JOptionPane.showMessageDialog(this, output);
    }//GEN-LAST:event_cbLocaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompoundMessageDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompoundMessageDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompoundMessageDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompoundMessageDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompoundMessageDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbLocale;
    // End of variables declaration//GEN-END:variables
}
